import { EditMap, Timepoint, NoteType } from "../MappingScope/EditMap";
import { entryList, assert } from "../Common/utils";
import { Music } from "../MappingPage/states";
import { NoteBase } from "bangbangboom-game/build/Core/RawMap";
import { Meta } from "../MappingScope/Meta";

type NoteData = {
  LaneId: number;
  Time: number;
};

type HachimiChartData = {
  BarLineList: number[];
  NoteDataList: NoteData[];
};

// thanks maomao
export function toHachimiFormat(map: EditMap, meta: Meta): string {
  const len = Music.duration;

  const chartData: HachimiChartData = {
    BarLineList: [],
    NoteDataList: [],
  };

  const tps: Timepoint[] = Array.from(map.timepoints.values())
    .sort((a, b) => a.time - b.time);

  {
    const [tp] = tps;

    if (!tp) {
      throw new Error('谱都没写你导个蛋')
    }
    const tpb = 60 / (tp.bpm / tp.bpb);

    chartData.BarLineList.push(tp.time);
    chartData.BarLineList.push(tp.time + tpb);
  }

  const chartNotes = Array.from(map.notes.values()).sort(
    (a: NoteType, b: NoteType) => {
      return a.offset - b.offset;
    }
  );

  chartNotes.forEach((note) => {
    const tp = assert(map.timepoints.get(note.timepoint));
    const tpOffset = 60 / (tp.bpm * 48);

    const time = tp.time + note.offset * tpOffset;
    const hachimiNote: NoteData = {
      LaneId: note.lane,
      Time: time,
    };

    chartData.NoteDataList.push(hachimiNote);
  });

  chartData.NoteDataList.sort((a, b) => a.Time - b.Time);

  if (meta.name.includes("\"") || meta.name.includes("'")) {
    throw new Error("曲名内不允许使用 \" 或者 ' ");
  }

  if (meta.chartName.includes("\"") || meta.chartName.includes("'")) {
    throw new Error("谱名内不允许使用 \" 或者 ' ");
  }

  const lines = ['// auto generated by bbb editor', "ent_fire s2ts-script Music_Begin"];
  lines.push(`ent_fire s2ts-script Music_SetName "${meta.name}"`);
  lines.push(`ent_fire s2ts-script Music_SetCharter "${meta.chartName}"`);
  lines.push(`ent_fire s2ts-script Music_SetSoundEvent "music.dummy_music"`);
  lines.push(`ent_fire s2ts-script Music_SetCover 1`);
  lines.push(`ent_fire s2ts-script Music_SetBarLines "${JSON.stringify([chartData.BarLineList[0], chartData.BarLineList[1]])}"`);
  for (const note of chartData.NoteDataList) {
    lines.push(`ent_fire s2ts-script Music_AddNote "${JSON.stringify([note.LaneId, note.Time])}"`);
  }
  lines.push(`ent_fire s2ts-script Music_End`);
  lines.push('');

  return lines.join('\n');
}
